[package]
name = "cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "cli"
test = false
bench = false

[lints]
workspace = true

[dependencies]
core = { path = "../core" } 
clap = { version = "4.5.41", features = ['derive'] } 
