[package]
name = "core"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
serde_json = "*"

[dev-dependencies]
insta = { version = "*", features = ['json'] }
