[package]
name = "core"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
serde_json = "*"
sqlparser = "0.57.0"

[dev-dependencies]
insta = { version = "*", features = ['json'] }
